baseurl = "/"
languageCode = "en-us"
Title = "sal.as"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
theme = "hugo_theme_pickles"


[params]
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  twitter = "franksalas"
  #facebook = "Your Facebook username"
  #instagram = "Your Instagram username"
  #googleplus = "Your Google+ user id"
  github = "franksalas"
  #npm = "Your npm username"
  #codepen = "Your CodePen username"
  #vimeo = "Your Vimeo username"
  #youtube = "Your YouTube username"
  linkedin = "Your LinkedIn username"
  # Disqus shortname
  #disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-105781975-1"
  author = "Francisco Salas"
  #authorwebsite = "about"
  avatar = "https://avatars1.githubusercontent.com/u/7411038?v=4&u=e22f5ebf6ee8baea460c6c7b8d2e8e6cb368ea01&s=400"
  bio = "I eat and I know things."
  # Short subtitle/tagline. This is displayed in the header.
  #subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
  #logo = "/path/to/logo"
  googleMapsAPIKey = ""


[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  hrefTargetBlank = true
  extensions = ["hardLineBreak"]
